# Generated by Django 3.2 on 2022-04-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='either',
            old_name='pick_a',
            new_name='issue_a',
        ),
        migrations.RenameField(
            model_name='either',
            old_name='pick_b',
            new_name='issue_b',
        ),
    ]
