# Generated by Django 3.2 on 2022-04-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0002_auto_20220414_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='either',
            name='issue_a',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='either',
            name='issue_b',
            field=models.CharField(max_length=100),
        ),
    ]
