# Generated by Django 3.2 on 2022-04-14 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0003_auto_20220414_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=100)),
                ('either', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eithers.either')),
            ],
        ),
    ]
