# Generated by Django 4.0.3 on 2022-04-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
    ]
