# Generated by Django 3.2.12 on 2022-04-13 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Comment',
        ),
    ]
